server:
  port: 8082

spring:
  application:
    name: feign-client-ms
  cloud:
    discovery:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
